### PR TITLE
CPU plugin: optional leading space instead of a zero (Fixes #2), prefix works (Fixes #1).

### LINKED ISSUE #1: Prefix does not work for CPU plugin
Prefix does not show up in front of the measurements.

### LINKED ISSUE #2: CPU plugin lacks possibility to switch between leading zero and space character

### PR DESCRIPTION
**Pull request by mkf**
CPU plugin: optional leading space instead of a zero (Fixes #2), prefix works (Fixes #1).

Idk whether #2 isn't about to be covered by a #7 solution though.

### CODE REVIEW

**Comment by XANi** [comment]
Maybe just expose option to change formatting string ? That way both `03.12%`, `3.12%`, `3%` or `03%`  would be possible.

I wonder if it is worth to rewrite plugins using "text/template". That would allow using something more verbose in formatting like `CPU Load:{{.Load}}`, [for example](https://play.golang.org/p/rWjRnsKC0J). Maybe not that useful for CPU but plugins like memory could benefit that

> Idk whether #2 isn't about to be covered by a #7 solution though.

This seems to be too specific option for that

**Comment by mkf** [comment]
Rewriting plugins using `text/template` takes time, and would be done in a separate branch for some time, so I think this PR could be merged for now. Regarding `text/template`, are you sure it's strings would be intuitive enough for everyone? Also, does it need to be somewhat like an interface for every plugin to support `text/template`? Memory plugin wouldn't benefit from it that much IMHO. Weather and battery plugins would indeed though.

**Comment by mkf** [comment]
Wait, it seems that somehow I have two spaces leading permanently.

**Comment by XANi** [comment]
> Regarding text/template, are you sure it's strings would be intuitive enough for everyone? 

Well it is not ideal but certainly be more intuitive than `%s<span color="%s">%s</span><span color="%s">%s</span>` or `%s<span color="%s">%s</span><span color="%s">%s</span>` that currently is used.

It also allows for hooking custom functions into template so for example it would be possible to have template looking like that: `CPU: {{barGraph .CpuLoad}} {{printf ""%05.2f" .CpuLoad}}%` producing `CPU: ▅ 40.13%`

> Also, does it need to be somewhat like an interface for every plugin to support text/template

I'd probably just pull it into util lib. It already have few helpers to do stuff like generating bargraph UTF symbols out of UTF chars or color palette. 

BTW if you modify pull request, merge changes into logical commits,(  `git rebase -i`  is one way). Doesn't really matter for tiny project like this but bigger projects usually complain when I didn't do that, same with commits that only fix mistake in previous commit or change whitespace

**Pull request merged**
